# Generated by Django 4.2.6 on 2023-10-17 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamillyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarriageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_id', models.IntegerField()),
                ('wife_id', models.IntegerField()),
                ('marriage_date', models.DateField()),
                ('devorced_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('death_date', models.DateField()),
                ('death_place', models.CharField(max_length=255)),
                ('father_id', models.IntegerField(max_length=255)),
                ('mother_id', models.IntegerField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('child_from_marriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritagehubapp.marriagemodel')),
                ('familly_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritagehubapp.famillymodel')),
            ],
        ),
        migrations.CreateModel(
            name='RelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_person_id', models.IntegerField()),
                ('relation_type', models.CharField(max_length=255)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritagehubapp.personmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritagehubapp.personmodel')),
            ],
        ),
    ]
