# Generated by Django 4.2.6 on 2023-10-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heritagehubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='heritagehubapp.personmodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='child_from_marriage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='heritagehubapp.marriagemodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='familly_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='heritagehubapp.famillymodel'),
        ),
        migrations.AlterField(
            model_name='relationmodel',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='heritagehubapp.personmodel'),
        ),
    ]
