# Generated by Django 4.2.6 on 2023-10-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heritagehubapp', '0003_alter_personmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='child_from_marriage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='heritagehubapp.marriagemodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='death_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='death_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='familly_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='heritagehubapp.famillymodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='father_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='mother_id',
            field=models.IntegerField(blank=True),
        ),
    ]
