# Generated by Django 4.2.6 on 2023-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritagehubapp', '0004_alter_personmodel_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
