# Generated by Django 4.2.6 on 2023-10-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heritagehubapp', '0005_alter_personmodel_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='child_from_marriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='heritagehubapp.marriagemodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='familly_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='heritagehubapp.famillymodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='father_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='mother_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
