# Generated by Django 4.2.6 on 2023-10-18 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heritagehubapp', '0006_alter_personmodel_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
