from .FamillyViewSetTests import FamillyViewSetTests
from .EventViewSetTests import EventViewSetTests
from .MarriageViewSetTests import MarriageViewSetTests
from .PersonViewSetTests import PersonViewSetTests
from .RelationViewSetTests import RelationViewSetTests