name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use python v3
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: create env and install requirements
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: make migrations
        run: |
          source env/bin/activate
          python manage.py makemigrations
          python manage.py migrate
      - name: run tests
        run: |
          source env/bin/activate
          python manage.py test
      - name: run server
        run: |
          source env/bin/activate
          python manage.py runserver
